import type { BlockRegistry } from "../registry";
import { AngleBlock } from "./angle/definition";
import { AngleBisectorBlock } from "./angle-bisector/definition";
import { AreaBlock } from "./area/definition";
import { CentroidBlock } from "./centroid/definition";
import { CircleFromCenterRadiusBlock } from "./circle-from-center-radius/definition";
import { CircleFromThreePointsBlock } from "./circle-from-three-points/definition";
import { ConicFromFivePointsBlock } from "./conic-from-five-points/definition";
import { DistanceBlock } from "./distance/definition";
import { IsCollinearBlock } from "./is-collinear/definition";
import { IsConcurrentBlock } from "./is-concurrent/definition";
import { IsParallelBlock } from "./is-parallel/definition";
import { IsPerpendicularBlock } from "./is-perpendicular/definition";
import { LineFromEquationBlock } from "./line-from-equation/definition";
import { LineFromPointsBlock } from "./line-from-points/definition";
import { MidpointBlock } from "./midpoint/definition";
import { PerimeterBlock } from "./perimeter/definition";
import { PerpendicularBisectorBlock } from "./perpendicular-bisector/definition";
import { PointBlock } from "./point/definition";
import { PolygonBlock } from "./polygon/definition";
import { RegularPolygonBlock } from "./regular-polygon/definition";

export function register(registry: BlockRegistry): void {
  registry.register(PointBlock);
  registry.register(LineFromPointsBlock);
  registry.register(LineFromEquationBlock);
  registry.register(CircleFromCenterRadiusBlock);
  registry.register(CircleFromThreePointsBlock);
  registry.register(PolygonBlock);
  registry.register(RegularPolygonBlock);
  registry.register(ConicFromFivePointsBlock);
  registry.register(MidpointBlock);
  registry.register(PerpendicularBisectorBlock);
  registry.register(AngleBisectorBlock);
  registry.register(DistanceBlock);
  registry.register(AngleBlock);
  registry.register(AreaBlock);
  registry.register(PerimeterBlock);
  registry.register(CentroidBlock);
  registry.register(IsCollinearBlock);
  registry.register(IsConcurrentBlock);
  registry.register(IsParallelBlock);
  registry.register(IsPerpendicularBlock);
}
