import type { BlockRegistry } from "../registry";
import { AffineBlock } from "./affine/definition";
import { AngleBlock } from "./angle/definition";
import { AngleBisectorBlock } from "./angle-bisector/definition";
import { AreaBlock } from "./area/definition";
import { CentroidBlock } from "./centroid/definition";
import { CircleFromCenterRadiusBlock } from "./circle-from-center-radius/definition";
import { CircleFromThreePointsBlock } from "./circle-from-three-points/definition";
import { ComposeBlock } from "./compose/definition";
import { ConicFromFivePointsBlock } from "./conic-from-five-points/definition";
import { DistanceBlock } from "./distance/definition";
import { GlideBlock } from "./glide/definition";
import { IntersectionBlock } from "./intersection/definition";
import { IsCollinearBlock } from "./is-collinear/definition";
import { IsConcurrentBlock } from "./is-concurrent/definition";
import { IsParallelBlock } from "./is-parallel/definition";
import { IsPerpendicularBlock } from "./is-perpendicular/definition";
import { LineFromEquationBlock } from "./line-from-equation/definition";
import { LineFromPointsBlock } from "./line-from-points/definition";
import { MidpointBlock } from "./midpoint/definition";
import { PerimeterBlock } from "./perimeter/definition";
import { PerpendicularBisectorBlock } from "./perpendicular-bisector/definition";
import { PointBlock } from "./point/definition";
import { PolygonBlock } from "./polygon/definition";
import { ProjectBlock } from "./project/definition";
import { ReflectBlock } from "./reflect/definition";
import { RegularPolygonBlock } from "./regular-polygon/definition";
import { RotateBlock } from "./rotate/definition";
import { ScaleBlock } from "./scale/definition";
import { TranslateBlock } from "./translate/definition";
import { VizConicClassifyBlock } from "./viz-conic-classify/definition";
import { VizGeometry2dBlock } from "./viz-geometry-2d/definition";
import { VizGeometry3dBlock } from "./viz-geometry-3d/definition";
import { VizTransformationAnimationBlock } from "./viz-transformation-animation/definition";

export function register(registry: BlockRegistry): void {
  registry.register(PointBlock);
  registry.register(LineFromPointsBlock);
  registry.register(LineFromEquationBlock);
  registry.register(CircleFromCenterRadiusBlock);
  registry.register(CircleFromThreePointsBlock);
  registry.register(PolygonBlock);
  registry.register(RegularPolygonBlock);
  registry.register(ConicFromFivePointsBlock);
  registry.register(MidpointBlock);
  registry.register(PerpendicularBisectorBlock);
  registry.register(AngleBisectorBlock);
  registry.register(DistanceBlock);
  registry.register(AngleBlock);
  registry.register(AreaBlock);
  registry.register(PerimeterBlock);
  registry.register(CentroidBlock);
  registry.register(IsCollinearBlock);
  registry.register(IsConcurrentBlock);
  registry.register(IsParallelBlock);
  registry.register(IsPerpendicularBlock);
  registry.register(TranslateBlock);
  registry.register(RotateBlock);
  registry.register(ReflectBlock);
  registry.register(ScaleBlock);
  registry.register(GlideBlock);
  registry.register(AffineBlock);
  registry.register(ComposeBlock);
  registry.register(ProjectBlock);
  registry.register(IntersectionBlock);
  registry.register(VizGeometry2dBlock);
  registry.register(VizGeometry3dBlock);
  registry.register(VizConicClassifyBlock);
  registry.register(VizTransformationAnimationBlock);
}
