import type { BlockRegistry } from "../registry";
import { AdjacencyMatrixBlock } from "./adjacency-matrix/definition";
import { BinomialBlock } from "./binomial/definition";
import { CartesianProductBlock } from "./cartesian-product/definition";
import { ColoringBlock } from "./coloring/definition";
import { CombinationsBlock } from "./combinations/definition";
import { ConnectedComponentsBlock } from "./connected-components/definition";
import { DifferenceBlock } from "./difference/definition";
import { DivisorsBlock } from "./divisors/definition";
import { FactorBlock } from "./factor/definition";
import { FactorialBlock } from "./factorial/definition";
import { FibonacciBlock } from "./fibonacci/definition";
import { GcdBlock } from "./gcd/definition";
import { GraphBlock } from "./graph/definition";
import { IntersectionBlock } from "./intersection/definition";
import { IsPrimeBlock } from "./is-prime/definition";
import { LcmBlock } from "./lcm/definition";
import { MinimumSpanningTreeBlock } from "./minimum-spanning-tree/definition";
import { ModpowBlock } from "./modpow/definition";
import { ModularInverseBlock } from "./modular-inverse/definition";
import { MultinomialBlock } from "./multinomial/definition";
import { PartialSumBlock } from "./partial-sum/definition";
import { PermutationsBlock } from "./permutations/definition";
import { PrimeFactorizeBlock } from "./prime-factorize/definition";
import { RecurrenceBlock } from "./recurrence/definition";
import { SetBlock } from "./set/definition";
import { ShortestPathBlock } from "./shortest-path/definition";
import { TotientBlock } from "./totient/definition";
import { UnionBlock } from "./union/definition";

export function register(registry: BlockRegistry): void {
  registry.register(SetBlock);
  registry.register(UnionBlock);
  registry.register(IntersectionBlock);
  registry.register(DifferenceBlock);
  registry.register(CartesianProductBlock);
  registry.register(FactorialBlock);
  registry.register(BinomialBlock);
  registry.register(MultinomialBlock);
  registry.register(GcdBlock);
  registry.register(LcmBlock);
  registry.register(ModpowBlock);
  registry.register(IsPrimeBlock);
  registry.register(FactorBlock);
  registry.register(TotientBlock);
  registry.register(DivisorsBlock);
  registry.register(PrimeFactorizeBlock);
  registry.register(ModularInverseBlock);
  registry.register(FibonacciBlock);
  registry.register(PartialSumBlock);
  registry.register(RecurrenceBlock);
  registry.register(PermutationsBlock);
  registry.register(CombinationsBlock);
  registry.register(GraphBlock);
  registry.register(AdjacencyMatrixBlock);
  registry.register(ShortestPathBlock);
  registry.register(MinimumSpanningTreeBlock);
  registry.register(ConnectedComponentsBlock);
  registry.register(ColoringBlock);
}
